
ERROR


Invalid operation: The `response.parts` quick accessor requires a single candidate, but but `response.candidates` is empty.
Traceback (most recent call last):
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py", line 54, in solve
    self._investigate(task, session_task)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py", line 137, in _investigate
    task_step = self.refine(
        session_task,
    ...<3 lines>...
        current_iteration,
    )
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py", line 231, in refine
    task_step = self._generate(
        session_task,
    ...<5 lines>...
        #  tools="code_execution"
    )
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py", line 178, in _generate
    task_step.log_response(response, response_time)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/session/task_step.py", line 151, in log_response
    self.log_markdown("response", [response.text])
                                   ^^^^^^^^^^^^^
  File "/home/phi/.pyenv/versions/3.13.2/lib/python3.13/site-packages/google/generativeai/types/generation_types.py", line 463, in text
    parts = self.parts
            ^^^^^^^^^^
  File "/home/phi/.pyenv/versions/3.13.2/lib/python3.13/site-packages/google/generativeai/types/generation_types.py", line 446, in parts
    raise ValueError(msg)
ValueError: Invalid operation: The `response.parts` quick accessor requires a single candidate, but but `response.candidates` is empty.

