{
  "context": "",
  "datetime": "2025-03-20T06:15:21.109576",
  "stack_trace": "Traceback (most recent call last):\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 58, in solve\n    self._investigate(task, session_task)\n    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 121, in _investigate\n    task_results = task_step.run_trials(task)\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/session/task_step.py\", line 265, in run_trials\n    code_trial = CodeTrial(self, code_filename, code, task)\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/trial_result.py\", line 41, in __init__\n    task_step._write_to_json(json_file, code_trial)\n                                        ^^^^^^^^^^\nNameError: name 'code_trial' is not defined. Did you mean: 'CodeTrial'?\n",
  "exception": "name 'code_trial' is not defined"
}