{
  "context": "",
  "datetime": "2025-03-24T11:56:03.578624",
  "stack_trace": "Traceback (most recent call last):\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 54, in solve\n    self._investigate(task, session_task)\n    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 117, in _investigate\n    task_step.run_trials()\n    ~~~~~~~~~~~~~~~~~~~~^^\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/session/task_step.py\", line 267, in run_trials\n    self.step_code_trials.run_trials()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/trials/step_code_trials.py\", line 26, in run_trials\n    code_trial = CodeTrial(self.task_step, code_filename, code, task)\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/trials/code_trial.py\", line 76, in __init__\n    results_image = self.task.to_image(\n        train_results=self.train_results,\n        test_results=self.test_results,\n        show_test=show_test,\n    )\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/tasks/tasks.py\", line 164, in to_image\n    train_images = get_table_images(self.train, train_results)\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/tasks/tasks.py\", line 158, in get_table_images\n    result_grid = Grid(result.transformed_output)\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/tasks/grid.py\", line 52, in __init__\n    self.grid = np.array(grid, dtype=int)\n                ~~~~~~~~^^^^^^^^^^^^^^^^^\nTypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'\n",
  "exception": "int() argument must be a string, a bytes-like object or a real number, not 'NoneType'"
}