{
  "context": "",
  "datetime": "2025-03-21T13:57:42.495952",
  "stack_trace": "Traceback (most recent call last):\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 54, in solve\n    self._investigate(task, session_task)\n    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 91, in _investigate\n    task_step.run_trials()\n    ~~~~~~~~~~~~~~~~~~~~^^\nTypeError: TaskStep.run_trials() missing 1 required positional argument: 'task'\n",
  "exception": "TaskStep.run_trials() missing 1 required positional argument: 'task'"
}