[2025-02-26T17:19:29.463430] ERROR: 'numpy.int64' object is not iterable
Traceback (most recent call last):
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py", line 94, in solve
    self._investigate(task)
    ~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py", line 177, in _investigate
    self._test_extracted_codelist(extracted_code_list, task)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py", line 189, in _test_extracted_codelist
    current_train_results = verifier.test_code(
        code,
        self.session.task_dir,
        task.train,
    )
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/verifier.py", line 83, in test_code
    ).to_string()
      ~~~~~~~~~^^
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/tasks/grid.py", line 206, in to_string
    return row_delimiter.join(
           ~~~~~~~~~~~~~~~~~~^
        cell_delimiter.join(str(cell) for cell in row) for row in self.grid
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/tasks/grid.py", line 207, in <genexpr>
    cell_delimiter.join(str(cell) for cell in row) for row in self.grid
                                              ^^^
TypeError: 'numpy.int64' object is not iterable


